saver:
	g++ -std=c++11 main.cpp screensaver.cpp -I/usr/local/Cellar/sfml/2.6.1/include -L/usr/local/Cellar/sfml/2.6.1/lib -lsfml-graphics -lsfml-window -lsfml-system -o saver

run:
	./saver

clean:
	rm -f *.o saver